const modal=document.getElementById('modal');
let supabaseClient=null;
function getSupabase(){if(supabaseClient)return supabaseClient;if(window.VICKIEARN_SUPABASE_URL&&window.VICKIEARN_SUPABASE_KEY&&window.supabase?.createClient){supabaseClient=window.supabase.createClient(window.VICKIEARN_SUPABASE_URL,window.VICKIEARN_SUPABASE_KEY);window.vickiearnSupabase=supabaseClient;}return supabaseClient;}
function copyReferral(){const v=document.getElementById('referralLink')?.textContent||'';if(v.startsWith('Sign in')){openModal('login');return;}navigator.clipboard?.writeText(v);const s=document.getElementById('copyStatus');if(s)s.textContent='Referral link copied.';}
function escapeHtml(v){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
async function loadUserData(){const c=getSupabase();if(!c?.auth)return;const {data:{user}}=await c.auth.getUser();if(!user)return;const [p,w,r,re]=await Promise.all([c.from('profiles').select('full_name,referral_code').eq('id',user.id).single(),c.from('wallets').select('balance_kobo,lifetime_earned_kobo').eq('user_id',user.id).single(),c.from('referrals').select('*',{count:'exact',head:true}).eq('referrer_id',user.id),c.from('transactions').select('amount_kobo').eq('user_id',user.id).eq('type','referral_reward')]);if(p.error||w.error)return;const bal=Number(w.data.balance_kobo||0)/100,earn=(re.data||[]).reduce((s,x)=>s+Number(x.amount_kobo||0),0)/100;const el=document.querySelector('.balance');if(el)el.textContent=`₦${bal.toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`;const link=document.getElementById('referralLink');if(link)link.textContent=`${location.origin}${location.pathname}?ref=${p.data.referral_code}`;document.getElementById('referralCount')?.replaceChildren(document.createTextNode(`${r.count||0} referrals`));document.getElementById('referralEarnings')?.replaceChildren(document.createTextNode(`₦${earn.toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`));}
async function loadTasks(){const grid=document.getElementById('taskGrid'),c=getSupabase();if(!grid||!c)return;const {data,error}=await c.from('tasks').select('id,title,description,reward_kobo,max_completions,completion_count').eq('status','active').order('created_at',{ascending:false});if(error){grid.innerHTML='<p>Tasks are temporarily unavailable.</p>';return;}if(!data?.length){grid.innerHTML='<p>No active tasks are available right now.</p>';return;}grid.innerHTML=data.map(t=>{const limit=t.max_completions!==null&&t.completion_count>=t.max_completions;return `<article class="task-card"><div class="task-icon">🎯</div><div><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.description)}</p></div><strong>₦${(Number(t.reward_kobo)/100).toLocaleString('en-NG')}</strong><button ${limit?'disabled':''} onclick="claimTask('${t.id}')">${limit?'Completed':'Start task'}</button></article>`}).join('');}
async function claimTask(id){const c=getSupabase();if(!c?.auth)return;const {data:{user}}=await c.auth.getUser();if(!user){openModal('login');return;}const {error}=await c.from('task_completions').insert({task_id:id,user_id:user.id,proof:{submitted_from:'web'}});if(error){alert(error.message);return;}alert('Task started. Your completion is pending review.');}

function normalizePhone(value){let p=String(value||'').trim().replace(/[\s().-]/g,'');if(p.startsWith('00'))p='+'+p.slice(2);if(/^0\d{10}$/.test(p))p='+234'+p.slice(1);else if(/^234\d{10}$/.test(p))p='+'+p;if(!/^\+[1-9]\d{7,14}$/.test(p))throw new Error('Enter a valid mobile number, e.g. 08012345678 or +2348012345678.');return p;}
let otpPending={phone:'',password:'',fullName:'',refCode:'',email:''};
function showOtpStep(){const title=document.getElementById('modalTitle'),text=document.getElementById('modalText'),form=document.getElementById('authForm');if(!form)return;title.textContent='Verify your mobile number';text.textContent=`Enter the 6-digit code sent by SMS to ${otpPending.phone}.`;form.innerHTML=`<input id="otpCode" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]{6}" placeholder="6-digit verification code" required><button class="btn btn-primary full" type="submit" id="otpSubmit">Verify number</button><button class="btn btn-light full" type="button" id="otpResend">Send code again</button><button class="btn btn-ghost full" type="button" id="otpBack">Back</button>`;form.onsubmit=verifySignupOtp;document.getElementById('otpResend').onclick=resendSignupOtp;document.getElementById('otpBack').onclick=()=>location.reload();document.getElementById('otpCode').focus();}
async function resendSignupOtp(){const c=getSupabase(),b=document.getElementById('otpResend');if(!c?.auth||!otpPending.phone)return;b.disabled=true;try{const {error}=await c.auth.signInWithOtp({phone:otpPending.phone,options:{shouldCreateUser:false}});if(error)throw error;status('A new verification code has been sent by SMS.');}catch(e){status(e.message||'Could not resend the code.',true);}finally{b.disabled=false;}}
async function verifySignupOtp(ev){ev.preventDefault();const c=getSupabase(),code=document.getElementById('otpCode')?.value.trim(),b=document.getElementById('otpSubmit');if(!/^\d{6}$/.test(code)){status('Enter the 6-digit code from the SMS.',true);return false;}b.disabled=true;b.textContent='Verifying…';status('Checking your verification code…');try{const {data,error}=await c.auth.verifyOtp({phone:otpPending.phone,token:code,type:'sms'});if(error)throw error;if(!data.session)throw new Error('Verification succeeded but no login session was returned. Please try Login.');const {error:passwordError}=await c.auth.updateUser({password:otpPending.password,data:{full_name:otpPending.fullName,referral_code:otpPending.refCode||null,email_address:otpPending.email||null,phone_number:otpPending.phone}});if(passwordError)throw passwordError;status('Mobile number verified. Opening your dashboard…');setTimeout(()=>location.href='dashboard.html',300);}catch(e){status(e.message||'Invalid or expired code. Please request a new code.',true);}finally{b.disabled=false;b.textContent='Verify number';}return false;}
async function handleAuthSubmitFromApp(ev){ev.preventDefault();const b=document.getElementById('authSubmit'),password=document.getElementById('password').value,full=document.getElementById('fullName').value.trim(),email=document.getElementById('email').value.trim(),ref=document.getElementById('refCode').value.trim().toUpperCase(),phoneRaw=document.getElementById('phone')?.value.trim()||'';if(!password){status('Enter your password.',true);return false;}if(password.length<8){status('Password must be at least 8 characters.',true);return false;}b.disabled=true;b.textContent=authMode==='signup'?'Sending SMS code…':'Signing in…';status('Connecting securely…');try{const c=getSupabase();if(!c)throw new Error('Authentication service did not load. Please refresh the page and try again.');if(authMode==='signup'){if(!full){throw new Error('Please enter your full name.');}const phone=normalizePhone(phoneRaw);otpPending={phone,password,fullName:full,refCode:ref,email};const {error}=await c.auth.signInWithOtp({phone,options:{shouldCreateUser:true,data:{full_name:full,referral_code:ref||null,email_address:email||null}}});if(error)throw error;showOtpStep();status('Verification code sent by SMS. Check your phone.');}else{const identifier=email;if(!identifier)throw new Error('Enter your email address or mobile number.');let r;if(identifier.includes('@'))r=await c.auth.signInWithPassword({email:identifier,password});else r=await c.auth.signInWithPassword({phone:normalizePhone(identifier),password});if(r.error)throw r.error;if(!r.data.session)throw new Error('No active session was returned.');status('Login successful. Opening your dashboard…');location.href='dashboard.html';}}catch(e){console.error(e);let m=e.message||'Authentication failed.';if(/rate limit|too many requests/i.test(m))m='Too many verification requests. Please wait a while before requesting another SMS code.';if(/already/i.test(m))m='That mobile number is already registered. Use Login instead.';if(/confirm/i.test(m))m='Please verify your mobile number before logging in.';status(m,true);}finally{b.disabled=false;if(document.getElementById('authSubmit'))b.textContent=authMode==='signup'?'Create account':'Log in';}return false;}
window.handleAuthSubmitFromApp=handleAuthSubmitFromApp;
window.handleAuthSubmit=handleAuthSubmitFromApp;
const c=getSupabase();if(c?.auth)c.auth.onAuthStateChange((_e,s)=>{if(s)loadUserData();});loadTasks();loadUserData();
