const db=window.vickiearnSupabase;
let currentUser=null,currentWallet={balance_kobo:0,lifetime_earned_kobo:0},currentTiers=[];
const $=id=>document.getElementById(id);
function showToast(msg){const e=$('toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>e.classList.remove('show'),3000)}
function money(k){return `₦${(Number(k||0)/100).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateText(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}
function toggleSidebar(){document.querySelector('.sidebar')?.classList.toggle('open');document.querySelector('.mobile-backdrop')?.classList.toggle('show')}
function closeSidebar(){document.querySelector('.sidebar')?.classList.remove('open');document.querySelector('.mobile-backdrop')?.classList.remove('show')}
function toggleNotifications(){const e=$('notificationDrawer');if(e)e.hidden=!e.hidden}
function openActionModal(html){const m=$('actionModal'),c=$('actionContent');if(!m||!c)return;c.innerHTML=html;m.hidden=false}
function closeActionModal(){const m=$('actionModal');if(m)m.hidden=true}
async function getUser(){if(!db)throw Error('Dashboard connection is unavailable.');const {data,error}=await db.auth.getUser();if(error)throw error;if(!data?.user)throw Error('Your session has expired. Please sign in again.');return data.user}
async function loadDashboard(){
 try{
  const user=await getUser();currentUser=user;
  const id=user.id;
  const profile=await db.from('profiles').select('full_name,role,referral_code').eq('id',id).maybeSingle();
  const wallet=await db.from('wallets').select('balance_kobo,lifetime_earned_kobo').eq('user_id',id).maybeSingle();
  currentWallet=wallet.data||{balance_kobo:0,lifetime_earned_kobo:0};
  const name=profile.data?.full_name||user.email||'Member';
  if($('profileName'))$('profileName').textContent=name;if($('profileRole'))$('profileRole').textContent=profile.data?.role==='admin'?'Administrator':'Member';if($('welcomeTitle'))$('welcomeTitle').textContent=`Welcome, ${name} 👋`;if($('avatar'))$('avatar').textContent=name.trim().charAt(0).toUpperCase()||'V';if($('adminLink')&&profile.data?.role==='admin')$('adminLink').hidden=false;if($('balanceValue'))$('balanceValue').textContent=money(currentWallet.balance_kobo);
  const tx=await db.from('transactions').select('type,amount_kobo,description,created_at').eq('user_id',id).order('created_at',{ascending:false}).limit(50);
  const refs=await db.from('referrals').select('id,created_at',{count:'exact'}).eq('referrer_id',id).order('created_at',{ascending:false}).limit(50);
  const tiers=await db.from('premium_tiers').select('id,name,amount_kobo,daily_task_limit,priority_rank,description').order('priority_rank');
  currentTiers=tiers.data||[];
  const tasks=await db.from('tasks').select('id,title,description,reward_kobo,status,max_completions,completion_count,required_tier_id').eq('status','active').order('created_at',{ascending:false});
  const membership=await db.from('premium_memberships').select('tier_id,status,activated_at,active_until').eq('user_id',id).eq('status','active').maybeSingle();
  const tier=membership.data&&currentTiers.find(t=>t.id===membership.data.tier_id);const activeMembership=membership.data&&tier&&(!membership.data.active_until||new Date(membership.data.active_until)>new Date())?{...membership.data,...tier}:null;
  renderPremium(activeMembership);renderTasks(tasks.data||[],activeMembership);renderTransactions(tx.data||[]);renderReferral(refs.count||0,profile.data?.referral_code);renderNotifications(tx.data||[],refs.data||[]);
  const list=tx.data||[];const taskEarn=list.filter(x=>x.type==='task_reward').reduce((s,x)=>s+Number(x.amount_kobo||0),0);const refEarn=list.filter(x=>x.type==='referral_reward').reduce((s,x)=>s+Number(x.amount_kobo||0),0);if($('taskEarnings'))$('taskEarnings').textContent=money(taskEarn);if($('referralEarningsMetric'))$('referralEarningsMetric').textContent=money(refEarn);if($('totalEarned'))$('totalEarned').textContent=money(currentWallet.lifetime_earned_kobo);if($('referralEarnings'))$('referralEarnings').textContent=money(refEarn);if($('walletMessage'))$('walletMessage').textContent=Number(currentWallet.balance_kobo)<500000?'Your balance is below the ₦5,000 withdrawal minimum.':'Your balance meets the withdrawal minimum.';
  showToast('Dashboard ready.');
 }catch(e){console.error('VickiEarn dashboard:',e);replaceLoadingStates('Unable to load this section. Tap Refresh to try again.');showToast(e.message||'Dashboard could not load.')}
}
function replaceLoadingStates(msg){['premiumStatus','taskList','transactionList','notificationList','drawerNotificationList'].forEach(id=>{const e=$(id);if(e&&/loading/i.test(e.textContent))e.innerHTML=`<p class="empty-state">${msg}</p>`});const r=$('referralInput');if(r&&/Preparing/i.test(r.value))r.value='Referral link unavailable — tap Refresh to retry.'}
function renderPremium(m){const e=$('premiumStatus');if(!e)return;e.innerHTML=m?`<b>★ ${esc(m.name)} — Active</b><small>Active until ${m.active_until?dateText(m.active_until):'—'} · Up to ${Number(m.daily_task_limit||0)} tasks/day.</small>`:'<b>Free access</b><small>No premium tier is active. You can still complete eligible free tasks.</small>'}
function renderTasks(tasks,m){const e=$('taskList');if(!e)return;const rank=Number(m?.priority_rank||0);const eligible=(tasks||[]).filter(t=>!t.required_tier_id||Number(currentTiers.find(x=>x.id===t.required_tier_id)?.priority_rank||0)<=rank);if(!eligible.length){e.innerHTML='<div class="task-empty"><b>No eligible tasks right now.</b><small>New tasks will appear here when available for your access level.</small><button class="small-btn" onclick="deposit()">View premium tiers</button></div>';return}e.innerHTML=eligible.map(t=>`<div class="task"><span class="task-icon">🎯</span><div><b>${esc(t.title)}</b><small>${esc(t.description||'Complete this eligible task.')}</small></div><strong>${money(t.reward_kobo)}</strong><button onclick="startTask('${t.id}')">Complete task</button></div>`).join('')}
function renderTransactions(items){const e=$('transactionList');if(!e)return;if(!items.length){e.innerHTML='<p class="empty-state">No transactions yet.</p>';return}e.innerHTML=items.slice(0,15).map(t=>`<div class="transaction"><span class="tx-icon">✓</span><div><b>${esc(t.description||t.type)}</b><small>${dateText(t.created_at)}</small></div><strong>${money(t.amount_kobo)}</strong></div>`).join('')}
function renderReferral(count,code){if($('referralCount'))$('referralCount').textContent=`${count} referral${count===1?'':'s'}`;const e=$('referralInput');if(e)e.value=code?`${location.origin}${location.pathname.replace(/dashboard\.html$/,'')}?ref=${encodeURIComponent(code)}`:'Referral link unavailable until your referral code is created.'}
function renderNotifications(tx,refs){const items=[...(tx||[]).map(t=>({title:t.type,text:t.description||'Account activity',date:t.created_at})),...(refs||[]).map(r=>({title:'New referral',text:'A new referral was recorded.',date:r.created_at}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,15);['notificationList','drawerNotificationList'].forEach(id=>{const e=$(id);if(!e)return;e.innerHTML=items.length?items.map(x=>`<div class="notification-item"><span>✓</span><div><b>${esc(x.title)}</b><p>${esc(x.text)}</p><small>${dateText(x.date)}</small></div></div>`).join(''):'<p class="empty-state">No notifications yet.</p>'})}
function deposit(){if(!currentTiers.length){showToast('Premium tiers are unavailable. Tap Refresh.');return}openActionModal(`<h2>Deposit & premium task access</h2><p>Choose a fixed premium tier. Payment is verified server-side before wallet credit.</p><div class="tier-grid">${currentTiers.map(t=>`<button class="tier-option" onclick="submitDepositTier('${t.id}',${Number(t.amount_kobo)})"><b>${esc(t.name)}</b><strong>${money(t.amount_kobo)}</strong><small>${esc(t.description||'Premium task access')}</small></button>`).join('')}</div><button class="secondary-action" onclick="closeActionModal()">Close</button>`)}
async function submitDepositTier(tier,amount){try{if(!window.VickiEarnPayments?.initializeDeposit)throw Error('Payment service is still loading. Refresh once.');await window.VickiEarnPayments.initializeDeposit(Number(amount)/100,tier)}catch(e){showToast(e.message||'Payment could not start.')}}
async function startTask(id){const r=await db.from('tasks').select('id,title,description,reward_kobo').eq('id',id).single();if(r.error){showToast('Task is unavailable.');return}openActionModal(`<h2>${esc(r.data.title)}</h2><p>${esc(r.data.description||'Complete the task and submit proof.')}</p><div class="action-note">Reward: <b>${money(r.data.reward_kobo)}</b></div><textarea id="taskProof" placeholder="Enter proof of completion…"></textarea><button class="primary-action" onclick="submitTask('${id}')">Submit task</button>`)}
async function submitTask(id){const proof=$('taskProof')?.value.trim();if(!proof||proof.length<10){showToast('Enter at least 10 characters of proof.');return}const r=await db.from('task_completions').insert({task_id:id,user_id:currentUser.id,proof:{submitted_from:'dashboard',details:proof}});if(r.error){showToast(r.error.message);return}closeActionModal();showToast('Task submitted for review.');await loadDashboard()}
async function requestWithdrawal(){try{const u=await getUser();const w=await db.from('wallets').select('balance_kobo').eq('user_id',u.id).maybeSingle();if(w.error)throw w.error;const balance=Number(w.data?.balance_kobo||0);openActionModal(`<h2>Withdraw money</h2><p>Minimum withdrawal: <b>₦5,000</b>. Available: <b>${money(balance)}</b></p>${balance>=500000?'<input id="withdrawAmount" type="number" min="5000" placeholder="Amount in Naira"><input id="accountName" placeholder="Account name"><input id="accountNumber" inputmode="numeric" maxlength="10" placeholder="10-digit account number"><input id="bankCode" inputmode="numeric" placeholder="Bank code"><button class="primary-action" onclick="submitWithdrawal()">Request withdrawal</button>':'<div class="action-note warning">You need at least ₦5,000 before you can submit a withdrawal.</div><button class="secondary-action" onclick="closeActionModal()">Close</button>'}`)}catch(e){showToast(e.message||'Unable to open withdrawals.')}}
async function submitWithdrawal(){const amount=Number($('withdrawAmount')?.value||0),name=$('accountName')?.value.trim(),number=$('accountNumber')?.value.trim(),bank=$('bankCode')?.value.trim();if(amount<5000||amount*100>Number(currentWallet.balance_kobo))return showToast('Check the withdrawal amount and balance.');if(!name||!/^[0-9]{10}$/.test(number)||!/^[0-9]{3,10}$/.test(bank))return showToast('Enter valid bank details.');const u=await getUser();const r=await db.rpc('create_withdrawal_request',{p_amount_kobo:Math.round(amount*100),p_account_name:name,p_account_number:number,p_bank_code:bank,p_user_id:u.id});if(r.error){showToast(r.error.message);return}closeActionModal();showToast('Withdrawal request submitted for admin processing.');await loadDashboard()}
async function copyLink(){const v=$('referralInput')?.value||'';if(!v||/unavailable|Preparing/i.test(v)){showToast('Referral link is not available yet.');return}try{await navigator.clipboard.writeText(v);showToast('Referral link copied.')}catch{showToast('Copy was blocked by the browser.')}}
async function shareLink(){const v=$('referralInput')?.value||'';if(!v||/unavailable|Preparing/i.test(v)){showToast('Referral link is not available yet.');return}try{if(navigator.share){await navigator.share({title:'Join VickiEarn',url:v});return}await navigator.clipboard.writeText(v);showToast('Referral link copied.')}catch(e){if(e?.name!=='AbortError')showToast('Unable to share right now.')}}
async function logout(){if(db)await db.auth.signOut();location.href='index.html'}
Object.assign(window,{loadDashboard,deposit,submitDepositTier,startTask,submitTask,requestWithdrawal,submitWithdrawal,copyLink,shareLink,logout,toggleSidebar,closeSidebar,toggleNotifications,openActionModal,closeActionModal,showToast});
window.addEventListener('load',()=>setTimeout(loadDashboard,300));
