const supabase=window.vickiearnSupabase;let currentUser=null;let currentProfile=null;
function showToast(message){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function toggleSidebar(){document.getElementById('sidebar')?.classList.toggle('open');document.querySelector('.mobile-backdrop')?.classList.toggle('show')}
function closeSidebar(){document.getElementById('sidebar')?.classList.remove('open');document.querySelector('.mobile-backdrop')?.classList.remove('show')}
function scrollToSection(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});closeSidebar()}
function naira(n){return `₦${(Number(n||0)/100).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function escapeHtml(v){return String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function fmtDate(v){try{return new Date(v).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}catch{return '—'}}
async function copyText(text){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);return true}catch{}}const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();return ok}
async function copyLink(){const input=document.getElementById('referralInput');if(!input||!input.value||input.value==='Loading…')return showToast('Referral link is still loading');const ok=await copyText(input.value);document.getElementById('copyStatus').textContent=ok?'Referral link copied.':'Select the link and copy it manually.';showToast(ok?'Referral link copied':'Copy was blocked by the browser')}
async function shareLink(){const input=document.getElementById('referralInput');if(!input?.value||input.value==='Loading…')return showToast('Referral link is still loading');const data={title:'Join VickiEarn',text:'Join me on VickiEarn and start earning. Use my referral link:',url:input.value};try{if(navigator.share){await navigator.share(data);showToast('Referral link ready to share');return}const ok=await copyText(input.value);showToast(ok?'Referral link copied — paste it into WhatsApp or another app.':'Copy was blocked by the browser')}catch(e){if(e?.name!=='AbortError')showToast('Could not open sharing')}
}
async function logout(){await supabase.auth.signOut();location.href='index.html'}
async function verifyPaymentReturn(){if(!window.VickiEarnPayments?.verifyReturnedPayment)return;const params=new URLSearchParams(location.search);if(params.get('reference')||params.get('trxref'))await window.VickiEarnPayments.verifyReturnedPayment()}
function transactionLabel(item){const labels={welcome_bonus:'Welcome bonus',task_reward:'Task reward',referral_reward:'Referral reward',deposit:'Deposit',withdrawal:'Withdrawal',withdrawal_reversal:'Withdrawal reversed'};return labels[item.type]||item.description||item.type||'Account activity'}
function renderNotifications(transactions,referrals){const box=document.getElementById('notificationList');if(!box)return;const items=[];(transactions||[]).slice(0,10).forEach(x=>items.push({date:x.created_at,title:transactionLabel(x),text:x.description||`${x.type} transaction of ${naira(x.amount_kobo)}`,amount:x.amount_kobo,type:x.type}));(referrals||[]).slice(0,10).forEach(x=>items.push({date:x.created_at,title:'Referral recorded',text:'A new account has been linked to your referral code.',type:'referral'}));items.sort((a,b)=>new Date(b.date)-new Date(a.date));if(!items.length){box.innerHTML='<p class="empty-state">No notifications yet. Account activity will appear here.</p>';document.getElementById('notificationDot')?.setAttribute('hidden','');return}box.innerHTML=items.slice(0,12).map(x=>{const positive=['welcome_bonus','task_reward','referral_reward','deposit'].includes(x.type);return `<div class="notification-item"><span class="notification-icon">${x.type==='referral'?'↗':positive?'✓':'↗'}</span><div><b>${escapeHtml(x.title)}</b><p>${escapeHtml(x.text)}</p><small>${fmtDate(x.date)}</small></div>${x.amount!==undefined?`<strong class="${positive?'positive':'negative'}">${positive?'+':'-'}${naira(x.amount)}</strong>`:''}</div>`}).join('');document.getElementById('notificationDot')?.removeAttribute('hidden')}
async function loadDashboard(){
 const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='index.html';return}currentUser=user;
 const [profile,wallet,refs,tx,tasks]=await Promise.all([
  supabase.from('profiles').select('full_name,referral_code,role').eq('id',user.id).single(),
  supabase.from('wallets').select('balance_kobo,lifetime_earned_kobo').eq('user_id',user.id).single(),
  supabase.from('referrals').select('id,referred_user_id,created_at',{count:'exact'}).eq('referrer_id',user.id).order('created_at',{ascending:false}).limit(20),
  supabase.from('transactions').select('type,amount_kobo,description,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(30),
  supabase.from('tasks').select('id,title,description,reward_kobo,status,max_completions,completion_count').eq('status','active').order('created_at',{ascending:false})
 ]);
 if(profile.error||wallet.error){showToast('Unable to load your account');return}currentProfile=profile.data;
 const name=profile.data?.full_name||user.email;document.querySelector('.profile b')?.replaceChildren(document.createTextNode(name));document.querySelector('.profile small')?.replaceChildren(document.createTextNode(profile.data?.role==='admin'?'Administrator':'Member'));document.querySelector('.topbar h1')?.replaceChildren(document.createTextNode(`Welcome, ${name} 👋`));const av=document.getElementById('avatar');if(av)av.textContent=(name||'V').trim().charAt(0).toUpperCase();if(profile.data?.role==='admin')document.getElementById('adminLink')?.removeAttribute('hidden');
 document.querySelector('.balance')?.replaceChildren(document.createTextNode(naira(wallet.data.balance_kobo)));
 const allTx=tx.data||[];const taskEarn=allTx.filter(x=>x.type==='task_reward').reduce((s,x)=>s+Number(x.amount_kobo||0),0);const refEarn=allTx.filter(x=>x.type==='referral_reward').reduce((s,x)=>s+Number(x.amount_kobo||0),0);const metrics=document.querySelectorAll('.metric b');if(metrics[0])metrics[0].textContent=naira(taskEarn);if(metrics[1])metrics[1].textContent=naira(refEarn);if(metrics[2])metrics[2].textContent=naira(wallet.data.lifetime_earned_kobo);const refAmount=document.querySelector('.ref-amount');if(refAmount)refAmount.textContent=naira(refEarn);const refCount=document.getElementById('referralCount');if(refCount)refCount.textContent=`${refs.count||0} referral${(refs.count||0)===1?'':'s'}`;
 const refInput=document.getElementById('referralInput');if(refInput)refInput.value=`${location.origin}${location.pathname.replace('dashboard.html','')}?ref=${encodeURIComponent(profile.data?.referral_code||'')}`;
 const taskPanel=document.querySelector('#tasks');if(taskPanel){taskPanel.querySelectorAll('.task,.task-empty').forEach(x=>x.remove());const list=tasks.data||[];if(!list.length){const empty=document.createElement('p');empty.className='task-empty';empty.textContent='No verified tasks are available right now. Check back soon.';taskPanel.appendChild(empty)}list.forEach(task=>{const row=document.createElement('div');row.className='task';const limit=task.max_completions!==null&&Number(task.completion_count)>=Number(task.max_completions);row.innerHTML=`<span class="task-icon">🎯</span><div><b>${escapeHtml(task.title)}</b><small>${escapeHtml(task.description||'Complete this task and submit proof.')}</small></div><strong>${naira(task.reward_kobo)}</strong><button ${limit?'disabled':''}>${limit?'Full':'Start'}</button>`;row.querySelector('button').onclick=()=>claimTask(task);taskPanel.appendChild(row)})}
 const history=document.querySelector('#history');if(history){history.querySelectorAll('.transaction').forEach(x=>x.remove());if(!allTx.length){const e=document.createElement('p');e.className='empty-state';e.textContent='No transactions yet.';history.appendChild(e)}allTx.slice(0,15).forEach(item=>{const row=document.createElement('div');row.className='transaction';const positive=!['withdrawal','withdrawal_reversal'].includes(item.type);row.innerHTML=`<span class="tx-icon">${positive?'✓':'↗'}</span><div><b>${escapeHtml(transactionLabel(item))}</b><small>${escapeHtml(item.description||'Account activity')} · ${fmtDate(item.created_at)}</small></div><strong class="${positive?'positive':'negative'}">${positive?'+':'-'}${naira(item.amount_kobo)}</strong>`;history.appendChild(row)})}
 renderNotifications(allTx,refs.data||[]);
}
async function claimTask(task){if(!currentUser)return;const existing=await supabase.from('task_completions').select('id,status').eq('task_id',task.id).eq('user_id',currentUser.id).maybeSingle();if(existing.data){showToast(existing.data.status==='approved'?'You already completed this task.':'This task is already awaiting review.');return}const proof=prompt(`Complete the task first, then enter your proof below.\n\n${task.description}\n\nProof (what you did, result, or reference):`);if(proof===null)return;if(proof.trim().length<10){showToast('Please provide at least 10 characters of useful proof.');return}const {error}=await supabase.from('task_completions').insert({task_id:task.id,user_id:currentUser.id,proof:{submitted_from:'dashboard',details:proof.trim()}});if(error)showToast(error.message);else{showToast('Task submitted for review. Rewards are credited after verification.');await loadDashboard()}}
async function requestWithdrawal(){const amount=prompt('Withdrawal amount in Naira (minimum ₦5,000):');if(!amount)return;const name=prompt('Account name:');const number=prompt('10-digit account number:');const bank=prompt('Bank code:');try{const id=await window.VickiEarnPayments.requestWithdrawal(amount,name,number,bank);showToast(`Withdrawal ${id} submitted`);await loadDashboard()}catch(e){showToast(e.message||'Withdrawal failed')}}
async function deposit(){const amount=prompt('Deposit amount in Naira:');if(!amount)return;try{await window.VickiEarnPayments.initializeDeposit(amount)}catch(e){showToast(e.message||'Payment could not start')}}
supabase?.auth.onAuthStateChange((_event,session)=>{if(!session)location.href='index.html'});(async()=>{await verifyPaymentReturn();await loadDashboard()})();